### PR TITLE
Cache NSDateFormatter objects for default formats

### PR DESCRIPTION
**Pull request by kylefleming**

### CODE REVIEW

**Review by BadChoice — COMMENTED** [review]
Aren't the singletons missing a 

`if(formatter != nil) return formatter`
before the dispatch_once ?

**Review by BadChoice — APPROVED** [review]
Thank you so much for the PR!! I'll merge and do some changes I think may make it a bit cleaner

**Comment by kylefleming** [comment]
`if(formatter != nil) return formatter`
isn't needed because after the first time, it'll just skip over the `dispatch_once` block and return immediately anyways.

See http://www.galloway.me.uk/tutorials/singleton-classes/

**Comment by kylefleming** [comment]
Glad you like the PR :) Caching this cleared up a huge source of performance issues for us. Thanks for the library!

**Comment by BadChoice** [comment]
Yeah.. I found about the `dispatch_once` thing after writting the comment hehe, I finally just changed the variables to static in the main class so the code gets a bit cleaner but the cached works the same.
Thank you so much for you contribution, I really appreciate it

**Pull request merged**
